apiVersion: v2
appVersion: 8.7.4
dependencies:
- name: ox-common
  repository: oci://registry.open-xchange.com/appsuite-core-internal/charts
  version: ~1.0.38
description: A Helm chart for appsuite core guidedtours
name: core-guidedtours
type: application
version: 2.8.3
