apiVersion: v2
appVersion: 8.48.0
dependencies:
- name: ox-common
  repository: oci://registry.open-xchange.com/appsuite-core-internal/charts
  version: ~1.0.38
description: A Helm chart for guard-ui
name: guard-ui
type: application
version: 2.48.0
