apiVersion: v2
appVersion: 3.1.2
dependencies:
- name: ox-common
  repository: oci://registry.open-xchange.com/appsuite-core-internal/charts
  version: ~1.0.51
- condition: minio.enabled
  name: minio
  repository: oci://registry-1.docker.io/bitnamicharts
  version: ~14.7.15
description: Helm chart for core ui middleware
name: core-ui-middleware
type: application
version: 4.4.4
