apiVersion: v2
appVersion: 2.3.3
dependencies:
- name: ox-common
  repository: oci://registry.open-xchange.com/appsuite-core-internal/charts
  version: ~1.0.38
description: Helm chart for core ui middleware
name: core-ui-middleware
type: application
version: 3.4.4
