{
 "title": "App Suite / Core-Imageconverter",
 "tags": [
  "java",
  "app-suite"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "query": "1m,5m,30m,1h,6h,1d" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(process_uptime_seconds{service=~\".*converter.*\"}, namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(process_uptime_seconds{namespace=\"$namespace\",service=~\".*imageconverter.*\"}, service)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(process_uptime_seconds{namespace=\"$namespace\",service=~\"$service\"}, pod)"
    }
   },
   {
    "name": "oc_group",
    "query": {
     "query": "label_values(objectcache_items_maximum_count{namespace=\"$namespace\",service=~\"$service\"}, group)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "non functional",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queue Time INSTANT ([[pod]])",
     "type": "stat",
     "description": "Instant Median Queue Time  ",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "imageconverter_queue_median_time_ms{pod=\"$pod\",queue=\"instant\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Up (services in [[namespace]])",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 3, "y": 25 },
     "targets": [
      {
       "expr": "up{namespace=~\"$namespace\"}\r\n",
       "legendFormat": "{{service}}-{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "IC Overview ( $service $pod )", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "ICs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{namespace=~\"$namespace\",service=~\"$service\"}\r\n",
     "legendFormat": "{{service}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Uptime ([[pod]])",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{service=~\"$service\",pod=~\"[[pod]]\"}",
     "legendFormat": "{{service}}"
    },
    {}
   ]
  },
  {
   "title": "Cache Hits ([[pod]])",
   "type": "gauge",
   "description": "red < 80%",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "imageconverter_cache_hit_ratio{pod=~\"[[pod]]\"} ",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Age Oldest Entry ([[pod]])",
   "type": "stat",
   "description": "yellow > 1h ; green > 1d",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "objectcache_oldest_modification_ms{group=\"OX_IC\",pod=~\"$pod\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Request Time Median  ($pod)",
   "type": "stat",
   "description": "max of all request types (yellow >3s ; red  >5s)",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(imageconverter_request_median_time_ms{pod=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IC Queing ([[pod]])",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Requests  / Keys Processed ([[pod]])",
     "type": "graph",
     "description": "Total Requests per second",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(imageconverter_request_count_total{pod=~\"$pod\"}[$interval])",
       "legendFormat": "IC Reqs {{pod}}"
      },
      {
       "expr": "rate(imageconverter_keys_processed_count{pod=~\"$pod\"}[$interval])",
       "legendFormat": "IC keys processed {{pod}}"
      }
     ]
    },
    {
     "title": "Request Limit Reached ([[pod]])",
     "type": "graph",
     "description": "Total Requests per second",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(imageconverter_request_limitreached_count{pod=~\"$pod\"}[1m])",
       "legendFormat": "IC {{job}} Limit {{request}}"
      }
     ]
    },
    {
     "title": "Queue median_time ([[pod]])",
     "type": "graph",
     "description": "Median Request Time ",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "imageconverter_queue_median_time_ms{pod=~\"$pod\"}",
       "legendFormat": "{{pod}} {{queue}} "
      }
     ]
    },
    {
     "title": "Request median_time per type ([[pod]])",
     "type": "graph",
     "description": "Median Request Time ",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 18 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "imageconverter_request_median_time_ms{pod=~\"$pod\"}",
       "legendFormat": "{{request}} {{pod}} "
      }
     ]
    },
    {
     "title": "Keys processing median_time ([[pod]])",
     "type": "graph",
     "description": "Median processing time - the conversion by imagemagick",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "imageconverter_keys_processed_median_time_ms{pod=~\"$pod\"}",
       "legendFormat": "{{pod}} {{request}}"
      }
     ]
    },
    {
     "title": "Requests per type ([[pod]])",
     "type": "graph",
     "description": "Total Requests per second",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(imageconverter_request_count{pod=~\"$pod\"}[1m])",
       "legendFormat": "IC {{pod}} {{request}}"
      }
     ]
    },
    {
     "title": "Peak per Queue ([[pod]])",
     "type": "graph",
     "description": "Total Requests per second",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "imageconverter_queue_peak_count{pod=~\"$pod\"}",
       "legendFormat": "IC {{pod}} {{queue}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IC Cache ([[pod]])",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "IC Cache Hits ([[pod]])",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "imageconverter_cache_hit_ratio{pod=~\"$pod\"}",
       "legendFormat": "CacheHits {{pod}}"
      }
     ]
    },
    {
     "title": "IC Cache Entries ([[pod]])",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "imageconverter_cache_key_count{pod=~\"$pod\"}",
       "legendFormat": "Entries {{pod}}"
      }
     ]
    },
    {
     "title": "IC Cache Size ([[pod]])",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "imageconverter_cache_size{pod=~\"$pod\"}",
       "legendFormat": "Entries {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IC Dimensions ([[pod]])",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top Request Dimensions",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 19, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "topk(4, max by(request) (sum by(request) (imageconverter_convert_dimensions{pod=~\"$pod\"})))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Dimensions Request and Target",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 19, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "imageconverter_convert_dimensions{pod=~\"$pod\"}",
       "legendFormat": "{{pod}} {{request}} - {{scaleType}} => {{target}} ({{format}})"
      }
     ]
    }
   ]
  },
  {
   "title": "IC ObjectCache ([[service]] [[pod]] [[oc_group]])",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Object Cache Item Count [[pod]]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "objectcache_items_current_count{pod=~\"$pod\",group=~\"$oc_group\"}",
       "legendFormat": "Keys {{group}} {{pod}}"
      }
     ]
    },
    {
     "title": "Object Cache Size [[pod]]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "objectcache_size_current_bytes{pod=~\"$pod\", group=~\"$oc_group\"}",
       "legendFormat": "Size {{group}} {{pod}}"
      }
     ]
    },
    {
     "title": "ObjectCache Max Size ($pod $oc_group)",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "objectcache_items_maximum_count{group=~\"$oc_group\"}",
       "legendFormat": "{{service}} {{pod}} {{group}} "
      }
     ]
    },
    {
     "title": "ObjectCache Max Bytes ($pod $oc_group)",
     "type": "stat",
     "gridPos": { "h": 6, "w": 11, "x": 12, "y": 44 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "objectcache_size_maximum_bytes{group=~\"$oc_group\"}",
       "legendFormat": "{{service}} {{pod}} {{group}} "
      }
     ]
    },
    {
     "title": "Object Cache Requests [[pod]]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(objectcache_request_count[1m])",
       "legendFormat": "{{group}} {{request}}"
      },
      {
       "expr": "rate(objectcache_request_count_total[1m])",
       "legendFormat": "total  {{group}}"
      }
     ]
    },
    {
     "title": "Median Request Time ([[pod]] [[oc_group]])",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "objectcache_request_medianduration_ms{pod=~\"$pod\",group=~\"oc_group\"}",
       "legendFormat": "{{pod}} {{group}} {{request}}"
      }
     ]
    },
    {
     "title": "Age Oldest Cache Entry ([[pod]] OX_IC)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "objectcache_oldest_modification_ms{group=\"OX_IC\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}} {{group}} {{request}}"
      }
     ]
    }
   ]
  }
 ]
}