{{- if (.Values.pdb).create }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ox-common.names.fullname" . }}
  labels:
    {{- include "ox-common.labels.standard" . | nindent 4 }}
spec:
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- else if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- else }}
  {{- fail "Either pdb.minAvailable or pdb.maxUnavailable must be set" }}
  {{- end }}
  {{- with .Values.pdb.unhealthyPodEvictionPolicy }}
  unhealthyPodEvictionPolicy: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ox-common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
{{- end }}
