{{- if and (or .Values.redis.auth.enabled .Values.redis.tls.enabled) (not .Values.overrides.redisSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "core-ui-middleware.redisSecret" . }}
type: Opaque
data:
  username: {{ .Values.redis.auth.username | b64enc | quote }}
  password: {{ .Values.redis.auth.password | b64enc | quote }}
  {{- if and .Values.redis.tls.enabled .Values.redis.tls.ca }}
  ca.crt: {{ .Values.redis.tls.ca | b64enc | quote }}
  {{- end }}
{{- end -}}
