{{- if and (eq (include "core-ui-middleware.storageBackend" .) "s3") (eq .Values.minio.enabled false) (not .Values.s3.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "core-ui-middleware.s3Secret" . }}
type: Opaque
data:
  {{ .Values.s3.auth.userSecretKey }}: {{ .Values.s3.auth.user | b64enc | quote }}
  {{ .Values.s3.auth.passwordSecretKey }}: {{ .Values.s3.auth.password | b64enc | quote }}
{{- end }}
