apiVersion: v2
appVersion: 8.51.0
dependencies:
- name: ox-common
  repository: oci://registry.open-xchange.com/appsuite-core-internal/charts
  version: 1.0.51
- alias: bookingservice
  condition: bookingservice.enabled, global.bookingservice.enabled
  name: booking
  repository: oci://registry.open-xchange.com/appsuite-core-internal/charts
  version: 0.5.2
- condition: core-mw.enabled, global.core-mw.enabled
  name: core-mw
  repository: oci://registry.open-xchange.com/appsuite-core-internal/charts
  tags:
  - preUpdate
  version: 6.22.6
- condition: core-documentconverter.enabled, global.core-documentconverter.enabled
  name: core-documentconverter
  repository: oci://registry.open-xchange.com/appsuite-core-internal/charts
  version: 2.49.0
- condition: core-imageconverter.enabled, global.core-imageconverter.enabled
  name: core-imageconverter
  repository: oci://registry.open-xchange.com/appsuite-core-internal/charts
  version: 2.50.1
- condition: core-ui.enabled, global.core-ui.enabled
  name: core-ui
  repository: oci://registry.open-xchange.com/appsuite-core-internal/charts
  version: 3.7.5
- condition: core-ui-middleware.enabled, global.core-ui-middleware.enabled
  name: core-ui-middleware
  repository: oci://registry.open-xchange.com/appsuite-core-internal/charts
  version: 4.4.4
- condition: core-user-guide.enabled, global.core-user-guide.enabled
  name: core-user-guide
  repository: oci://registry.open-xchange.com/appsuite-core-internal/charts
  version: 2.51.0
- condition: guard-ui.enabled, global.guard-ui.enabled
  name: guard-ui
  repository: oci://registry.open-xchange.com/appsuite-core-internal/charts
  version: 2.51.0
- condition: appsuite-toolkit.enabled, global.appsuite-toolkit.enabled
  name: appsuite-toolkit
  repository: oci://registry.open-xchange.com/appsuite-core-internal/charts
  version: 1.18.0
- condition: switchboard.enabled, global.switchboard.enabled
  name: switchboard
  repository: oci://registry.open-xchange.com/appsuite-core-internal/charts
  version: 5.8.8
description: A Helm chart for setting up AppSuite services on Kubernetes
name: appsuite-public-sector-base
type: application
version: 8.51.808
