---
global:
  extras:
    monitoring:
      enabled: false
  useDefaultSecurityContext: true
  core-cacheservice:
    enabled: true
nameOverride: ''
fullnameOverride: ''
createCommonEnv: true
istio:
  enabled: false
  ingressGateway:
    name: ''
    hosts: []
    overridableHosts: {}
    selector: ingressgateway
    tls:
      enabled: false
      existingSecret: ''
      minProtocolVersion: TLSV1_2
  securityHeaders:
    enabled: false
  destinationRules:
    appsuite:
      tls:
        mode: DISABLE
    dav:
      tls:
        mode: DISABLE
    businessmobility:
      tls:
        mode: DISABLE
  virtualServices:
    appsuite:
      hosts: []
      overridableHosts: {}
      extraRoutes: []
      extraRouteProperties: {}
    dav:
      enabled: true
      hosts: []
      overridableHosts: {}
      extraRoutes: []
      extraRouteProperties: {}
    businessmobility:
      enabled: false
      hosts: []
      overridableHosts: {}
      extraRoutes: []
      extraRouteProperties: {}
  extraVirtualServices: {}
  segmentedRouting:
    enabled: false
    localSite: ''
    sites: []
    appsuitePaths:
    - "/api"
    - "/ajax"
    - "%%APP_ROOT%%/api"
    - "/pks"
    - "/rt2"
    - "/admin"
    - "/advertisement"
    - "/chronos"
    - "/preliminary"
    - "/userfeedback"
    - "/servlet"
    - "/realtime"
    - "/infostore"
    - "/webservices"
    davPaths:
    - "/"
    businessmobilityPaths:
    - "/usm-json"
    - "/Microsoft-Server-ActiveSync"
ingress:
  enabled: false
  adapter: appsuite.ingress.ingress-nginx
  annotations: {}
  tls:
    enabled: false
    existingSecret: ''
  appsuite:
    hosts: []
    overridableHosts: {}
  dav:
    enabled: true
    hosts: []
    overridableHosts: {}
  switchboard:
    enabled: false
    hosts: []
    overridableHosts: {}
  businessmobility:
    enabled: false
    hosts: []
    overridableHosts: {}
  routes:
    appsuite-base:
      enabled: true
      annotations: {}
      annotationMode: Add
    rootredirect:
      enabled: true
      annotations: {}
      annotationMode: Add
    trailslash:
      enabled: true
      annotations: {}
      annotationMode: Add
    rest-routes-admin:
      enabled: true
      annotations: {}
      annotationMode: Add
    rest-routes-advertisement:
      enabled: true
      annotations: {}
      annotationMode: Add
    rest-routes-chronos:
      enabled: true
      annotations: {}
      annotationMode: Add
    rest-routes-preliminary:
      enabled: true
      annotations: {}
      annotationMode: Add
    rest-routes-userfeedback:
      enabled: true
      annotations: {}
      annotationMode: Add
    static-routes-servlet:
      enabled: true
      annotations: {}
      annotationMode: Add
    static-routes-realtime:
      enabled: true
      annotations: {}
      annotationMode: Add
    static-routes-infostore:
      enabled: true
      annotations: {}
      annotationMode: Add
    static-routes-webservices:
      enabled: true
      annotations: {}
      annotationMode: Add
    drive-client-windows-ox-route:
      enabled: true
      annotations: {}
      annotationMode: Add
    guard-api-route:
      enabled: true
      annotations: {}
      annotationMode: Add
    guard-support-api-route:
      enabled: true
      annotations: {}
      annotationMode: Add
    guard-pgp-route:
      enabled: true
      annotations: {}
      annotationMode: Add
    http-api-routes-api:
      enabled: true
      annotations: {}
      annotationMode: Add
    http-api-routes-ajax:
      enabled: true
      annotations: {}
      annotationMode: Add
    http-api-routes-appsuite-api:
      enabled: true
      annotations: {}
      annotationMode: Add
    http-api-routes-app-root-api:
      enabled: true
      annotations: {}
      annotationMode: Add
    rt2-route:
      enabled: true
      annotations: {}
      annotationMode: Add
    documents-help-route:
      enabled: true
      annotations: {}
      annotationMode: Add
    drive-help-route:
      enabled: true
      annotations: {}
      annotationMode: add
    core-help-route:
      enabled: true
      annotations: {}
      annotationMode: add
    office-web-route:
      enabled: true
      annotations: {}
      annotationMode: add
    caldav-well-known-redirect:
      enabled: true
      annotations: {}
      annotationMode: add
    carddav-well-known-redirect:
      enabled: true
      annotations: {}
      annotationMode: add
    dav-infostore-route:
      enabled: true
      annotations: {}
      annotationMode: add
    dav-root-route:
      enabled: true
      annotations: {}
      annotationMode: add
    switchboard-root-route:
      enabled: true
      annotations: {}
      annotationMode: add
    wopi-server-route:
      enabled: false
      annotations: {}
      annotationMode: add
    core-ui-api-route:
      enabled: true
      annotations: {}
      annotationMode: add
    businessmobility-microsoft-route:
      enabled: true
      annotations: {}
      annotationMode: add
      timeout: 1900
    businessmobility-usm-route:
      enabled: true
      annotations: {}
      annotationMode: add
      timeout: 1900
redis:
  core-mw:
    enabled: false
    customConfig:
    - maxmemory-policy allkeys-lru
    - maxmemory-samples 10
    replicaCount: 3
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 500Mi
    sentinelCustomConfig: []
    sentinelReplicaCount: 3
    sentinelResources:
      requests:
        cpu: 100m
      limits:
        memory: 100Mi
    metrics:
      enabled: false
      imageSentinelExporter: leominov/redis_sentinel_exporter:1.7.1
      imageRedisExporter: oliver006/redis_exporter:v1.53.0-alpine
  core-ui-middleware:
    enabled: false
    customConfig:
    - maxmemory-policy allkeys-lru
    - maxmemory-samples 10
    replicaCount: 3
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 500Mi
    sentinelCustomConfig: []
    sentinelReplicaCount: 3
    sentinelResources:
      requests:
        cpu: 100m
      limits:
        memory: 100Mi
    metrics:
      enabled: false
      imageSentinelExporter: leominov/redis_sentinel_exporter:1.7.1
      imageRedisExporter: oliver006/redis_exporter:v1.53.0-alpine
  switchboard:
    enabled: false
    customConfig:
    - maxmemory-policy allkeys-lru
    - maxmemory-samples 10
    replicaCount: 3
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 500Mi
    sentinelCustomConfig: []
    sentinelReplicaCount: 3
    sentinelResources:
      requests:
        cpu: 100m
      limits:
        memory: 100Mi
    metrics:
      enabled: false
      imageSentinelExporter: leominov/redis_sentinel_exporter:1.7.1
      imageRedisExporter: oliver006/redis_exporter:v1.53.0-alpine
core-mw:
  enabled: true
  createCommonEnv: false
  image:
    repository: appsuite-public-sector/middleware
    tag: 8.49.108
  update:
    image:
      repository: appsuite-public-sector/middleware
      tag: 8.49.108
    defaultRegistry: registry.open-xchange.com
    podAnnotations:
      commit.open-xchange.com/core: 3c8142d923a892c38d4ffad13904aefb10efc626
      commit.open-xchange.com/guard: bde4037fd1e6e549a6f1f6b03ce652fd6838d762
      commit.open-xchange.com/office: 07515efccd817a36150bfd2a62c6f11153a370eb
      commit.open-xchange.com/weakforced: 45315409d6114849f50419c1b3efc33d387c4b3f
  podAnnotations:
    commit.open-xchange.com/core: 3c8142d923a892c38d4ffad13904aefb10efc626
    commit.open-xchange.com/guard: bde4037fd1e6e549a6f1f6b03ce652fd6838d762
    commit.open-xchange.com/office: 07515efccd817a36150bfd2a62c6f11153a370eb
    commit.open-xchange.com/weakforced: 45315409d6114849f50419c1b3efc33d387c4b3f
  defaultRegistry: registry.open-xchange.com
  packages:
    status:
      open-xchange-drive-client-windows: enabled
    configuration:
      sessiond:
        redis:
          enabled: true
    redis:
      enabled: true
  gotenberg:
    image:
      repository: registry.open-xchange.com/appsuite-public-sector/gotenberg
      tag: 8.15.3
    podAnnotations: {}
  collabora-online:
    image:
      repository: registry.open-xchange.com/appsuite-public-sector/collabora-online@sha256
      tag: '0686d50956c3ef1baa44f91165186fcbe1663f98f298010058f12e39f6abab40'
    podAnnotations: {}
core-user-guide:
  enabled: true
  image:
    repository: appsuite-public-sector/core-user-guide
    tag: 8.49.2476344551
  podAnnotations:
    commit.open-xchange.com/user-guide: 906c2a58e2757b0f31d06efed75bfeaf8ba4e9d3
  defaultRegistry: registry.open-xchange.com
core-documentconverter:
  enabled: true
  createCommonEnv: false
  image:
    repository: appsuite-public-sector/documentconverter
    tag: 8.49.2095
  podAnnotations:
    commit.open-xchange.com/documentconverter: 6fb0a5c771a1893e3386f817def1cd3d7b10515c
  defaultRegistry: registry.open-xchange.com
core-imageconverter:
  enabled: true
  createCommonEnv: false
  image:
    repository: appsuite-public-sector/imageconverter
    tag: 8.49.2587
  podAnnotations:
    commit.open-xchange.com/imageconverter: 89e2539a0f5b96c298d235b5d647f705788196ee
  defaultRegistry: registry.open-xchange.com
core-ui:
  enabled: true
  image:
    repository: appsuite-public-sector/core-ui
    tag: 8.49.3
  podAnnotations:
    commit.open-xchange.com/ui: d9a1dde54fce6873d1d84b2a86d073f2f29af6b1
  defaultRegistry: registry.open-xchange.com
core-ui-middleware:
  enabled: true
  image:
    repository: appsuite-public-sector/core-ui-middleware
    tag: 2.3.3
  podAnnotations:
    commit.open-xchange.com/ui-service: d7e243e044b79f20cf1ff2ca46203538c89094e5
  existingConfigMap: "{{ .Release.Name }}-core-ui-middleware"
  defaultRegistry: registry.open-xchange.com
  redis:
    enabled: false
extraUIManifestURLs: []
overridableExtraUIManifestURLs: {}
core-guidedtours:
  enabled: true
  image:
    repository: appsuite-public-sector/core-guidedtours
    tag: 8.7.4
  podAnnotations:
    commit.open-xchange.com/guidedtours: 64d52474a6695de59c48ec792ba06760615e7ae9
  defaultRegistry: registry.open-xchange.com
guard-ui:
  enabled: true
  image:
    repository: appsuite-public-sector/guard-ui
    tag: 8.49.0
  podAnnotations:
    commit.open-xchange.com/guard-ui: 931b091b301cc61a3ddcb06218073eeb18cbf1f1
  defaultRegistry: registry.open-xchange.com
switchboard:
  enabled: true
  image:
    repository: appsuite-public-sector/switchboard
    tag: 5.3.2
  podAnnotations:
    commit.open-xchange.com/switchboard: ea2b152ed4cdf499cb7071d1fda6c1ab9fd32478
  defaultRegistry: registry.open-xchange.com
extras:
  monitoring:
    enabled: false
    serviceMonitor:
      namespace: ''
      interval: 30s
      scrapeTimeout: ''
      relabelings:
      - sourceLabels:
        - __meta_kubernetes_pod_label_app_kubernetes_io_name
        targetLabel: app
      metricRelabelings: []
      honorLabels: false
      additionalLabels: {}
      annotations: {}
tags:
  preUpdate: false
appsuite-toolkit:
  enabled: true
  replicaCount: 0
  defaultRegistry: registry.open-xchange.com
  image:
    repository: appsuite-public-sector/appsuite-toolkit
    tag: 1.16.1781328
  mwctl:
    image:
      repository: appsuite-public-sector/middleware-debug
      tag: 2.0.1888592
    defaultRegistry: registry.open-xchange.com
    podAnnotations:
      commit.open-xchange.com/middleware-debug: add5352b6ac00aea6e59f9d26e8403a7ca415982
  podAnnotations:
    commit.open-xchange.com/appsuite-toolkit: 017faad1450f3fe6593778fdcf45ad0a46138dab
