apiVersion: v2
appVersion: 0.1.1
dependencies:
- name: ox-common
  repository: oci://registry.open-xchange.com/appsuite-core-internal/charts
  version: ~1.0.43
name: owncloud-integration-ui
type: application
version: 0.1.1
