{
 "title": "App Suite / Core-Documentconverter",
 "tags": [
  "java",
  "app-suite"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "query": "1m,5m,30m,1h,6h,1d" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(process_uptime_seconds{service=~\".*converter.*\"}, namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(process_uptime_seconds{namespace=\"$namespace\",service=~\".*documentconverter.*\"}, service)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(process_uptime_seconds{namespace=\"$namespace\",service=~\"$service\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "DC Overview ([[service]] [[pod]])",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "DCs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{namespace=~\"$namespace\",service=~\"$service\"}\r\n",
     "legendFormat": "{{service}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Uptime ([[pod]])",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{service=~\"$service\",pod=~\"[[pod]]\"}",
     "legendFormat": "{{service}}"
    },
    {}
   ]
  },
  {
   "title": "Cache Hits ([[pod]])",
   "type": "gauge",
   "description": "red < 75%",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "documentconverter_cache_hit_ratio{pod=~\"[[pod]]\"} ",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Age Oldest Entry ([[pod]])",
   "type": "stat",
   "description": "yellow > 1h ; green > 1d",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "documentconverter_cache_oldest_entry_age_seconds{pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Request Success ([[pod]])",
   "type": "gauge",
   "description": "red < 75%",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "documentconverter_user_requests_success_ratio{type=\"all\",pod=~\"$pod\"} ",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "MW Request Exceptions ([[pod]])",
   "type": "stat",
   "description": "Ratio of failing connection attempts for requests;\nNaN means no conversion requests during last interval; No data means no exceptions",
   "gridPos": { "h": 6, "w": 3, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(appsuite_documentconverterclient_connections_convert_count{status!=\"ok\"}[$interval])) / sum(increase(appsuite_documentconverterclient_connections_convert_count[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MW Connections to DC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "DC Client Validations",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 14, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "increase(appsuite_documentconverterclient_connections_validation_count[$interval])",
       "legendFormat": "{{instance}} {{pod}} {{status}}"
      }
     ]
    },
    {
     "title": "Validation Errors",
     "type": "stat",
     "gridPos": { "h": 9, "w": 5, "x": 14, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(appsuite_documentconverterclient_connections_validation_count{status!=\"ok\"}[$interval])) / sum(increase(appsuite_documentconverterclient_connections_validation_count[$interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DC Client Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 14, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(appsuite_documentconverterclient_connections_convert_count[$interval])",
       "legendFormat": "{{instance}} {{pod}} {{status}}"
      }
     ]
    },
    {
     "title": "Request Exceptions",
     "type": "stat",
     "description": "Ratio of failing connection attempts for requests;\nNaN means no conversion requests during last interval",
     "gridPos": { "h": 8, "w": 5, "x": 14, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(appsuite_documentconverterclient_connections_convert_count{status!=\"ok\"}[$interval])) / sum(increase(appsuite_documentconverterclient_connections_convert_count[$interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Peaks and Limits ([[pod]])",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Limits ([[pod]])",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "documentconverter_jobs_queue_limit_total{pod=~\"$pod\"}",
       "legendFormat": "{{pod}} {{limit}}"
      }
     ]
    },
    {
     "title": "Async Dropped ([[pod]])",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "increase(documentconverter_jobs_asyncqueue_dropped_total[$interval])",
       "legendFormat": "dropped {{pod}}"
      }
     ]
    },
    {
     "title": "Peaks ([[pod]])",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "documentconverter_jobs_peak_count{pod=~\"$pod\",priority!=\"all\"}",
       "legendFormat": "Peak {{priority}} {{pod}} "
      }
     ]
    },
    {
     "title": "Async Peaks ([[pod]])",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "documentconverter_jobs_peak_count_asyncQueue{pod=~\"$pod\"}",
       "legendFormat": "AsyncPeak {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DC Queing ([[pod]])",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "DC Jobs ([[pod]])",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(documentconverter_jobs_processed_total{pod=~\"$pod\"}[1m])",
       "legendFormat": "JobsProcessed {{pod}}"
      },
      {
       "expr": "increase(documentconverter_jobs_processed_error_total{pod=~\"$pod\"}[1m])",
       "legendFormat": "JobsErrors {{pod}}"
      },
      {
       "expr": "increase(documentconverter_conversions_readerengine_total{pod=~\"$pod\"}[1m])",
       "legendFormat": "REConvs {{pod}}"
      }
     ]
    },
    {
     "title": "Scheduled Jobs ([[pod]])",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "documentconverter_jobs_scheduled_total{pod=~\"$pod\"}",
       "legendFormat": " {{pod}}"
      }
     ]
    },
    {
     "title": "Median Wait Time ([[pod]])",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "documentconverter_jobs_median_time_waiting_ms{pod=~\"$pod\",priority=\"all\"}",
       "legendFormat": "wait time {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DC Async Queue ([[pod]])",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Async Queue Scheduling ([[pod]])",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "increase(documentconverter_jobs_asyncqueue_processed_total{pod=~\"$pod\"}[$interval])",
       "legendFormat": "processed {{pod}}"
      },
      {
       "expr": "documentconverter_jobs_asyncqueue_scheduled_total{pod=\"$pod\"}",
       "legendFormat": "scheduled {{pod}}"
      }
     ]
    },
    {
     "title": "Async Queue Peak ([[pod]])",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "documentconverter_jobs_asyncqueue_peak_total",
       "legendFormat": "peak {{pod}} "
      },
      { "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "DC Cache ([[pod]])",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "DC Cache Hits ([[pod]])",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "documentconverter_cache_hit_ratio{pod=~\"$pod\"}",
       "legendFormat": "CacheHit {{pod}}"
      },
      {
       "expr": "documentconverter_errorcache_hit_ratio{pod=~\"$pod\"}",
       "legendFormat": "ErrorCacheHit {{pod}}"
      }
     ]
    },
    {
     "title": "DC Cache Entries ([[pod]])",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "documentconverter_cache_entry_count{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "DC Cache Size ([[pod]])",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "documentconverter_cache_entry_size{pod=~\"$pod\"}",
       "legendFormat": "Size {{pod}}"
      }
     ]
    },
    {
     "title": "Oldest Entry ([[pod]])",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "documentconverter_cache_oldest_entry_age_seconds{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DC User Requests Statistics ([[pod]])",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Success Ratio  by Type ([[pod]])",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "documentconverter_user_requests_success_ratio{pod=~\"$pod\",type!=\"xall\"}",
       "legendFormat": "Type {{type}} {{pod}}"
      }
     ]
    },
    {
     "title": "User requests ([[pod]])",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(documentconverter_user_requests_count{pod=~\"$pod\",type!=\"all\"}[1m])",
       "legendFormat": "{{pod}} {{type}}"
      }
     ]
    },
    {
     "title": "User Request Fails ([[pod]])",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 11, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(documentconverter_user_requests_failed_count{pod=~\"$pod\",type!=\"all\"}[1m])",
       "legendFormat": "{{pod}} {{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DC Errors ([[pod]])",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "DC Jobs ([[pod]])",
     "type": "graph",
     "gridPos": { "h": 8, "w": 19, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(documentconverter_jobs_processed_total{pod=~\"$pod\"}[1m])",
       "legendFormat": "JobsProcessed {{pod}}"
      },
      {
       "expr": "increase(documentconverter_jobs_processed_error_total{pod=~\"$pod\"}[1m])",
       "legendFormat": "JobsErrors {{pod}}"
      },
      {
       "expr": "increase(documentconverter_conversions_readerengine_total{pod=~\"$pod\"}[1m])",
       "legendFormat": "REConvs {{pod}}"
      }
     ]
    },
    {
     "title": "DC Jobs Error Ratio ([[pod]])",
     "type": "graph",
     "gridPos": { "h": 9, "w": 19, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "increase(documentconverter_jobs_processed_error_total{pod=~\"$pod\"}[$interval]) / increase(documentconverter_jobs_processed_total{pod=~\"$pod\"}[$interval])",
       "legendFormat": "Job Error Ratio {{pod}}"
      }
     ]
    },
    {
     "title": "RE Errors ([[pod]])",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(documentconverter_conversions_readerengine_error_total{pod=~\"$pod\"}[1m])",
       "legendFormat": "RE Errors {{pod}} {{error}}"
      }
     ]
    },
    {
     "title": "DC Error Cache Hits ([[pod]])",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "documentconverter_errorcache_hit_ratio{pod=~\"$pod\"}",
       "legendFormat": "ErrorCacheHit {{pod}}"
      }
     ]
    }
   ]
  }
 ]
}