---
appsuite:
  overridableExtraUIManifestURLs:
    nextcloud-integration: http://%%RELEASE-NAME%%-nextcloud-integration-ui/manifest.json
    public-sector: http://%%RELEASE-NAME%%-public-sector-ui/manifest.json
  core-mw:
    image:
      repository: appsuite-public-sector/middleware-public-sector
      tag: 8.49.113
    defaultRegistry: registry.open-xchange.com
    podAnnotations:
      commit.open-xchange.com/core: '068850e644ec2b2e95fb073d4bdd704f0e98907c'
      commit.open-xchange.com/exchange-interop: e43f77b956c8fa0bb49f8ed4d075e3c3de8f1351
      commit.open-xchange.com/guard: bde4037fd1e6e549a6f1f6b03ce652fd6838d762
      commit.open-xchange.com/nextcloud-integration: 8cf1b742aff361973f638204afcb05eb59e53dcc
      commit.open-xchange.com/office: 07515efccd817a36150bfd2a62c6f11153a370eb
      commit.open-xchange.com/public-sector: 241b800594d74df1ab2846050d986e1ace48723e
      commit.open-xchange.com/weakforced: 45315409d6114849f50419c1b3efc33d387c4b3f
    update:
      image:
        repository: appsuite-public-sector/middleware-public-sector
        tag: 8.49.113
      defaultRegistry: registry.open-xchange.com
      podAnnotations:
        commit.open-xchange.com/core: '068850e644ec2b2e95fb073d4bdd704f0e98907c'
        commit.open-xchange.com/exchange-interop: e43f77b956c8fa0bb49f8ed4d075e3c3de8f1351
        commit.open-xchange.com/guard: bde4037fd1e6e549a6f1f6b03ce652fd6838d762
        commit.open-xchange.com/nextcloud-integration: 8cf1b742aff361973f638204afcb05eb59e53dcc
        commit.open-xchange.com/office: 07515efccd817a36150bfd2a62c6f11153a370eb
        commit.open-xchange.com/public-sector: 241b800594d74df1ab2846050d986e1ace48723e
        commit.open-xchange.com/weakforced: 45315409d6114849f50419c1b3efc33d387c4b3f
nextcloud-integration-ui:
  enabled: true
  image:
    repository: appsuite-public-sector/nextcloud-integration-ui
    tag: 1.4.2
  defaultRegistry: registry.open-xchange.com
  podAnnotations:
    commit.open-xchange.com/nextcloud-integration-ui: '068ac0ea76cd2dc4028201169edc52ea8fb252b2'
public-sector-ui:
  enabled: true
  image:
    repository: appsuite-public-sector/public-sector-ui
    tag: 2.6.2
  defaultRegistry: registry.open-xchange.com
  podAnnotations:
    commit.open-xchange.com/public-sector-ui: 241b800594d74df1ab2846050d986e1ace48723e
