{
 "title": "App Suite / Core-Middleware",
 "description": "App Suite Core Middleware Dashboard\n",
 "tags": [
  "java",
  "app-suite"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(appsuite_version_info, namespace)"
   },
   {
    "name": "app",
    "query": "label_values(up{namespace=\"$namespace\"}, app)"
   },
   {
    "name": "pod",
    "query": "label_values(appsuite_version_info{namespace=\"$namespace\", app=~\".*$app.*\"}, pod)"
   },
   {
    "name": "dbpool",
    "query": "label_values(appsuite_mysql_connections_total{namespace=\"$namespace\"}, pool)"
   },
   {
    "name": "httpclient",
    "query": "label_values(appsuite_httpclient_requests_seconds_count, client)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Server Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "topk(1, count(\n  appsuite_version_info{pod=~\"$pod\", namespace=\"$namespace\"}\n  ) by (server_version)\n)\n",
     "legendFormat": "{{server_version}}\n"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "process_uptime_seconds{pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Health Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "topk(1, count(\n  appsuite_health_status{\n    pod=\"$pod\"\n  } > 0)\n)\n"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Overview",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "appsuite_sessions_total{\n  client=\"all\",\n  namespace=\"$namespace\",\n  pod=~\"$pod\"\n}\n",
       "legendFormat": "Total"
      },
      {
       "expr": "appsuite_sessions_active_total{\n  client=\"all\",\n  namespace=\"$namespace\",\n  pod=~\"$pod\"\n}\n",
       "legendFormat": "Active"
      },
      {
       "expr": "appsuite_sessions_short_term_total{\n  client=\"all\",\n  namespace=\"$namespace\",\n  pod=~\"$pod\"\n}\n",
       "legendFormat": "Short Term"
      },
      {
       "expr": "appsuite_sessions_long_term_total{\n  client=\"all\",\n  namespace=\"$namespace\",\n  pod=~\"$pod\"\n}\n",
       "legendFormat": "Long Term"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis (Lettuce)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Command Completion",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (command) (\n  rate(\n    lettuce_command_completion_seconds_sum{\n      pod=~\"$pod\",\n      namespace=~\"$namespace\"\n    }[$__rate_interval]\n  )\n) /\nsum by (command) (\n  rate(\n    lettuce_command_completion_seconds_count{\n      pod=~\"$pod\",\n      namespace=~\"$namespace\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{command}}"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "appsuite_redis_connections_num_active{\n  pod=~\"$pod\",\n  namespace=~\"$namespace\",\n  name=\"redis-pool\"\n}\n",
       "legendFormat": "Active"
      },
      {
       "expr": "appsuite_redis_connections_num_idle{\n  pod=~\"$pod\",\n  namespace=~\"$namespace\",\n  name=\"redis-pool\"\n}\n",
       "legendFormat": "Idle"
      },
      {
       "expr": "appsuite_redis_connections_num_waiters{\n  pod=~\"$pod\",\n  namespace=~\"$namespace\",\n  name=\"redis-pool\"\n}\n",
       "legendFormat": "Waiters"
      },
      {
       "expr": "appsuite_redis_connections_num_total{\n  pod=~\"$pod\",\n  namespace=~\"$namespace\",\n  name=\"redis-pool\"\n}\n",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Cache Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "appsuite_redis_cache_connections_num_active{\n  pod=~\"$pod\",\n  namespace=~\"$namespace\",\n  name=\"redis-cache-pool\"\n}\n",
       "legendFormat": "Active"
      },
      {
       "expr": "appsuite_redis_cache_connections_num_idle{\n  pod=~\"$pod\",\n  namespace=~\"$namespace\",\n  name=\"redis-cache-pool\"\n}\n",
       "legendFormat": "Idle"
      },
      {
       "expr": "appsuite_redis_cache_connections_num_waiters{\n  pod=~\"$pod\",\n  namespace=~\"$namespace\",\n  name=\"redis-cache-pool\"\n}\n",
       "legendFormat": "Waiters"
      },
      {
       "expr": "appsuite_redis_cache_connections_num_total{\n  pod=~\"$pod\",\n  namespace=~\"$namespace\",\n  name=\"redis-cache-pool\"\n}\n",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  {
   "title": "ThreadPool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "ThreadPool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "targets": [
      {
       "expr": "appsuite_executor_active_threads{\n  name=\"main\",\n  pod=\"$pod\"\n}\n",
       "legendFormat": "ActiveCount"
      },
      {
       "expr": "appsuite_executor_pool_size_threads{\n  name=\"main\",\n  pod=\"$pod\"\n}\n",
       "legendFormat": "PoolSize"
      }
     ]
    },
    {
     "title": "ThreadPool Tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "targets": [
      {
       "expr": "appsuite_executor_queue_remaining_tasks{\n  name=\"main\",\n  pod=~\"$pod\"\n}\n",
       "legendFormat": "Remaining"
      },
      {
       "expr": "appsuite_executor_queued_tasks{\n  name=\"main\",\n  pod=~\"$pod\"\n}\n",
       "legendFormat": "Queued"
      },
      {
       "expr": "rate(\n  appsuite_executor_completed_tasks_total{\n    name=\"main\",\n    pod=~\"$pod\"\n  }[$__rate_interval])\n",
       "legendFormat": "Completed"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Hits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(module) (\n  rate(\n    appsuite_redis_cache_hits_total{\n      pod=~\"$pod\"\n    }\n    [$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{module}}"
      }
     ]
    },
    {
     "title": "Cache Misses",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(module) (\n  rate(\n    appsuite_redis_cache_misses_total{\n      pod=~\"$pod\"\n    }\n    [$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{module}}"
      }
     ]
    },
    {
     "title": "Cache Hit/Miss Ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(\n  rate(\n    appsuite_redis_cache_hits_total{\n      pod=\"$pod\"\n    }\n    [$__rate_interval]\n  )\n) / (\n  sum(\n    rate(\n      appsuite_redis_cache_hits_total{\n        pod=\"$pod\"\n      }\n      [$__rate_interval]\n    )\n  ) + sum(\n    rate(\n      appsuite_redis_cache_misses_total{\n        pod=\"$pod\"\n      }\n      [$__rate_interval]\n    )\n  )\n)\n",
       "legendFormat": "Hit Ratio"
      },
      {
       "expr": "sum(\n  rate(\n    appsuite_redis_cache_misses_total{\n      pod=\"$pod\"\n      }\n      [$__rate_interval]\n    )\n  )\n/ (\n  sum(\n    rate(\n      appsuite_redis_cache_hits_total{\n        pod=\"$pod\"\n      }\n      [$__rate_interval]\n    )\n  )\n  + sum(\n    rate(\n      appsuite_redis_cache_misses_total{\n        pod=\"$pod\"\n      }\n      [$__rate_interval]\n    )\n  )\n)\n",
       "legendFormat": "Miss Ratio"
      }
     ]
    },
    {
     "title": "Cache Puts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(module) (\n  rate(\n    appsuite_redis_cache_puts_total{\n      pod=~\"$pod\"\n    }\n    [$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{module}}"
      }
     ]
    },
    {
     "title": "Cache Removals",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(module) (\n  rate(\n    appsuite_redis_cache_removals_total{\n      pod=~\"$pod\"\n    }\n    [$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{module}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DB Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "ConfigDB Read Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "appsuite_mysql_connections_total{class=\"configdb\",pod=~\"$pod\",type=\"read\"}\n",
       "legendFormat": "Pooled"
      },
      {
       "expr": "appsuite_mysql_connections_active{class=\"configdb\",pod=\"$pod\",type=\"read\"}\n",
       "legendFormat": "Active"
      },
      {
       "expr": "appsuite_mysql_connections_idle{class=\"configdb\",pod=~\"$pod\",type=\"read\"}\n",
       "legendFormat": "Idle"
      },
      {
       "expr": "sum(appsuite_mysql_connections_max{class=\"configdb\",pod=~\"$pod\",type=\"read\"})\n",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "ConfigDB Write Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "appsuite_mysql_connections_total{class=\"configdb\",pod=~\"$pod\",type=\"write\"}\n",
       "legendFormat": "Pooled"
      },
      {
       "expr": "appsuite_mysql_connections_active{class=\"configdb\",pod=\"$pod\",type=\"write\"}\n",
       "legendFormat": "Active"
      },
      {
       "expr": "appsuite_mysql_connections_idle{class=\"configdb\",pod=~\"$pod\",type=\"write\"}\n",
       "legendFormat": "Idle"
      },
      {
       "expr": "sum(appsuite_mysql_connections_max{class=\"configdb\",pod=~\"$pod\",type=\"write\"})\n",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "UserDB Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "appsuite_mysql_connections_total{\n  class=~\"userdb\",\n  pod=~\"$pod\",\n  pool=~\"$dbpool\"\n}\n",
       "legendFormat": "Pooled (Type: {{type}}, Pool: {{pool}})\n"
      },
      {
       "expr": "appsuite_mysql_connections_active{\n  class=~\"userdb\",\n  pod=~\"$pod\",\n  pool=~\"$dbpool\"\n}\n",
       "legendFormat": "Active (Type: {{type}}, Pool: {{pool}})\n"
      },
      {
       "expr": "appsuite_mysql_connections_idle{\n  class=~\"userdb\",\n  pod=~\"$pod\",\n  pool=~\"$dbpool\"\n}\n",
       "legendFormat": "Idle (Type: {{type}}, Pool: {{pool}})\n"
      },
      {
       "expr": "appsuite_mysql_connections_max{\n  class=~\"userdb\",\n  pod=~\"$pod\",\n  pool=~\"$dbpool\"\n}\n",
       "legendFormat": "Max (Type: {{type}}, Pool: {{pool}})\n"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Client ($httpclient)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests (per-second)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (client, instance) (\n  rate(\n    appsuite_httpclient_requests_seconds_count{\n      pod=~\"$pod\",\n      client=\"$httpclient\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "Total"
      },
      {
       "expr": "sum by (client, instance) (\n  rate(\n    appsuite_httpclient_requests_seconds_count{\n      pod=~\"$pod\",\n      client=\"$httpclient\",\n      status!~\"[45][0-9]{2}\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "OK"
      },
      {
       "expr": "sum by (client, instance) (\n  rate(\n    appsuite_httpclient_requests_seconds_count{\n      pod=~\"$pod\",\n      client=\"$httpclient\",\n      status=~\"[45][0-9]{2}\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "KO"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "targets": [
      {
       "expr": "appsuite_httpclient_connections_pending{\n  pod=\"$pod\",\n  client=~\"$httpclient\"\n}\n",
       "legendFormat": "Pending"
      },
      {
       "expr": "appsuite_httpclient_connections_available{\n  pod=\"$pod\",\n  client=~\"$httpclient\"\n}\n",
       "legendFormat": "Available"
      },
      {
       "expr": "appsuite_httpclient_connections_leased{\n  pod=\"$pod\",\n  client=~\"$httpclient\"\n}\n",
       "legendFormat": "Leased"
      },
      {
       "expr": "appsuite_httpclient_connections_max{\n  pod=\"$pod\",\n  client=~\"$httpclient\"\n}\n",
       "legendFormat": "Max"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests (per-second)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(\n  rate(\n    appsuite_httpapi_requests_seconds_count{\n      pod=~\"$pod\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(\n  rate(\n    appsuite_httpapi_requests_seconds_count{\n      status=~\"OK\",\n      pod=~\"$pod\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "OK"
      },
      {
       "expr": "sum(\n  rate(\n    appsuite_httpapi_requests_seconds_count{\n      status!~\"OK\",\n      pod=~\"$pod\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "KO"
      }
     ]
    },
    {
     "title": "Response Time Percentiles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.90,\n  sum by (namespace, le, pod) (\n    rate(\n      appsuite_httpapi_requests_seconds_bucket{\n        namespace=~\"$namespace\",\n        pod=~\"$pod\"\n      }[$__rate_interval]\n    )\n  )\n)\n",
       "legendFormat": "p90\n"
      },
      {
       "expr": "histogram_quantile(\n  0.95,\n  sum by (namespace, le, pod) (\n    rate(\n      appsuite_httpapi_requests_seconds_bucket{\n        namespace=~\"$namespace\",\n        pod=~\"$pod\"\n      }[$__rate_interval]\n    )\n  )\n)\n",
       "legendFormat": "p95\n"
      },
      {
       "expr": "histogram_quantile(\n  0.99,\n  sum by (namespace, le, pod) (\n    rate(\n      appsuite_httpapi_requests_seconds_bucket{\n        namespace=~\"$namespace\",\n        pod=~\"$pod\"\n      }[$__rate_interval]\n    )\n  )\n)\n",
       "legendFormat": "p99\n"
      },
      {
       "expr": "sum by (namespace, le, pod) (\n  rate(\n    appsuite_httpapi_requests_seconds_sum{\n        namespace=~\"$namespace\",\n        pod=~\"$pod\"\n    }[$__rate_interval])\n) /\nsum by (namespace, le, pod) (\n  rate(\n    appsuite_httpapi_requests_seconds_count{\n      namespace=~\"$namespace\",\n      pod=~\"$pod\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "mean"
      }
     ]
    },
    {
     "title": "Top 5 Requests (99th percentile)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(\n  5,\n  histogram_quantile(\n    0.99, sum by (le, module, action, instance) (\n      rate(\n        appsuite_httpapi_requests_seconds_bucket{\n          pod=~\"$pod\"\n        }[${__range_s}s]\n      )\n    )\n  )\n)\n",
       "legendFormat": "{{module}}/{{action}}\n"
      }
     ]
    }
   ]
  },
  {
   "title": "REST API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests (per-second)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(\n  rate(\n    appsuite_restapi_requests_seconds_count{\n      pod=~\"$pod\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(\n  rate(\n    appsuite_restapi_requests_seconds_count{\n      status=~\"OK\",\n      pod=~\"$pod\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "OK"
      },
      {
       "expr": "sum(\n  rate(\n    appsuite_restapi_requests_seconds_count{\n      status!~\"OK\",\n      pod=~\"$pod\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "KO"
      }
     ]
    },
    {
     "title": "Response Time Percentiles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.90,\n  sum by (namespace, le, pod) (\n    rate(\n      appsuite_restapi_requests_seconds_bucket{\n        namespace=~\"$namespace\",\n        pod=~\"$pod\"\n      }[$__rate_interval]\n    )\n  )\n)\n",
       "legendFormat": "p90\n"
      },
      {
       "expr": "histogram_quantile(\n  0.95,\n  sum by (namespace, le, pod) (\n    rate(\n      appsuite_restapi_requests_seconds_bucket{\n        namespace=~\"$namespace\",\n        pod=~\"$pod\"\n      }[$__rate_interval]\n    )\n  )\n)\n",
       "legendFormat": "p95\n"
      },
      {
       "expr": "histogram_quantile(\n  0.99,\n  sum by (namespace, le, pod) (\n    rate(\n      appsuite_restapi_requests_seconds_bucket{\n        namespace=~\"$namespace\",\n        pod=~\"$pod\"\n      }[$__rate_interval]\n    )\n  )\n)\n",
       "legendFormat": "p99\n"
      },
      {
       "expr": "sum by (namespace, le, pod) (\n  rate(\n    appsuite_restapi_requests_seconds_sum{\n        namespace=~\"$namespace\",\n        pod=~\"$pod\"\n    }[$__rate_interval])\n) /\nsum by (namespace, le, pod) (\n  rate(\n    appsuite_restapi_requests_seconds_count{\n      namespace=~\"$namespace\",\n      pod=~\"$pod\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "mean"
      }
     ]
    }
   ]
  },
  {
   "title": "WebDAV API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests (per-second)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(\n  rate(\n    appsuite_webdav_requests_seconds_count{\n      pod=~\"$pod\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(\n  rate(\n    appsuite_webdav_requests_seconds_count{\n      status=~\"OK\",\n      pod=~\"$pod\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "OK"
      },
      {
       "expr": "sum(\n  rate(\n    appsuite_webdav_requests_seconds_count{\n      status!~\"OK\",\n      pod=~\"$pod\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "KO"
      }
     ]
    },
    {
     "title": "Response Time Percentiles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.90,\n  sum by (namespace, le, pod) (\n    rate(\n      appsuite_webdav_requests_seconds_bucket{\n        namespace=~\"$namespace\",\n        pod=~\"$pod\"\n      }[$__rate_interval]\n    )\n  )\n)\n",
       "legendFormat": "p90\n"
      },
      {
       "expr": "histogram_quantile(\n  0.95,\n  sum by (namespace, le, pod) (\n    rate(\n      appsuite_webdav_requests_seconds_bucket{\n        namespace=~\"$namespace\",\n        pod=~\"$pod\"\n      }[$__rate_interval]\n    )\n  )\n)\n",
       "legendFormat": "p95\n"
      },
      {
       "expr": "histogram_quantile(\n  0.99,\n  sum by (namespace, le, pod) (\n    rate(\n      appsuite_webdav_requests_seconds_bucket{\n        namespace=~\"$namespace\",\n        pod=~\"$pod\"\n      }[$__rate_interval]\n    )\n  )\n)\n",
       "legendFormat": "p99\n"
      },
      {
       "expr": "sum by (namespace, le, pod) (\n  rate(\n    appsuite_webdav_requests_seconds_sum{\n        namespace=~\"$namespace\",\n        pod=~\"$pod\"\n    }[$__rate_interval])\n) /\nsum by (namespace, le, pod) (\n  rate(\n    appsuite_webdav_requests_seconds_count{\n      namespace=~\"$namespace\",\n      pod=~\"$pod\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "mean"
      }
     ]
    }
   ]
  },
  {
   "title": "SOAP API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests (per-second)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(\n  rate(\n    appsuite_soapapi_requests_seconds_count{\n      pod=~\"$pod\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(\n  rate(\n    appsuite_soapapi_requests_seconds_count{\n      status=~\"OK\",\n      pod=~\"$pod\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "OK"
      },
      {
       "expr": "sum(\n  rate(\n    appsuite_soapapi_requests_seconds_count{\n      status!~\"OK\",\n      pod=~\"$pod\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "KO"
      }
     ]
    },
    {
     "title": "Response Time Percentiles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.90,\n  sum by (namespace, le, pod) (\n    rate(\n      appsuite_soapapi_requests_seconds_bucket{\n        namespace=~\"$namespace\",\n        pod=~\"$pod\"\n      }[$__rate_interval]\n    )\n  )\n)\n",
       "legendFormat": "p90\n"
      },
      {
       "expr": "histogram_quantile(\n  0.95,\n  sum by (namespace, le, pod) (\n    rate(\n      appsuite_soapapi_requests_seconds_bucket{\n        namespace=~\"$namespace\",\n        pod=~\"$pod\"\n      }[$__rate_interval]\n    )\n  )\n)\n",
       "legendFormat": "p95\n"
      },
      {
       "expr": "histogram_quantile(\n  0.99,\n  sum by (namespace, le, pod) (\n    rate(\n      appsuite_soapapi_requests_seconds_bucket{\n        namespace=~\"$namespace\",\n        pod=~\"$pod\"\n      }[$__rate_interval]\n    )\n  )\n)\n",
       "legendFormat": "p99\n"
      },
      {
       "expr": "sum by (namespace, le, pod) (\n  rate(\n    appsuite_soapapi_requests_seconds_sum{\n        namespace=~\"$namespace\",\n        pod=~\"$pod\"\n    }[$__rate_interval])\n) /\nsum by (namespace, le, pod) (\n  rate(\n    appsuite_soapapi_requests_seconds_count{\n      namespace=~\"$namespace\",\n      pod=~\"$pod\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "mean"
      }
     ]
    }
   ]
  },
  {
   "title": "Provisioning",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Requests (per-second)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(\n  rate(\n    appsuite_provisioning_api_duration_seconds_count{\n      pod=~\"$pod\"\n    }\n    [$__rate_interval]\n  )\n)\n",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(\n  rate(\n    appsuite_provisioning_api_duration_seconds_count{\n      status=~\"OK\",\n      pod=~\"$pod\"\n    }\n    [$__rate_interval]\n  )\n)\n",
       "legendFormat": "OK"
      },
      {
       "expr": "sum(\n  rate(\n    appsuite_provisioning_api_duration_seconds_count{\n      status!~\"OK\",\n      pod=~\"$pod\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "KO"
      }
     ]
    },
    {
     "title": "Plugin Requests (per-second)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(\n  rate(\n    appsuite_provisioning_plugin_duration_seconds_count{\n      pod=~\"$pod\"\n    }\n    [$__rate_interval]\n  )\n)\n",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(\n  rate(\n    appsuite_provisioning_plugin_duration_seconds_count{\n      status=~\"OK\",\n      pod=~\"$pod\"\n    }\n    [$__rate_interval]\n  )\n)\n",
       "legendFormat": "OK"
      },
      {
       "expr": "sum(\n  rate(\n    appsuite_provisioning_plugin_duration_seconds_count{\n      status!~\"OK\",\n      pod=~\"$pod\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "KO"
      }
     ]
    },
    {
     "title": "Storage Requests (per-second)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(\n  rate(\n    appsuite_provisioning_storage_duration_seconds_count{\n      pod=~\"$pod\"\n    }\n    [$__rate_interval]\n  )\n)\n",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(\n  rate(\n    appsuite_provisioning_storage_duration_seconds_count{\n      status=~\"OK\",\n      pod=~\"$pod\"\n    }\n    [$__rate_interval]\n  )\n)\n",
       "legendFormat": "OK"
      },
      {
       "expr": "sum(\n  rate(\n    appsuite_provisioning_storage_duration_seconds_count{\n      status!~\"OK\",\n      pod=~\"$pod\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "KO"
      }
     ]
    },
    {
     "title": "Average API Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (api_class, method, operation) (\n  rate(\n    appsuite_provisioning_api_duration_seconds_sum{\n      pod=~\"$pod\",\n      namespace=~\"$namespace\"\n    }[$__rate_interval]\n  )\n) /\nsum by (api_class, method, operation) (\n  rate(\n    appsuite_provisioning_api_duration_seconds_count{\n      pod=~\"$pod\",\n      namespace=~\"$namespace\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{api_class}} - {{method}} - {{operation}}\n"
      }
     ]
    },
    {
     "title": "Average Plugin Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (plugin_name, method, operation) (\n  rate(\n    appsuite_provisioning_plugin_duration_seconds_sum{\n      pod=~\"$pod\",\n      namespace=~\"$namespace\"\n    }[$__rate_interval]\n  )\n) /\nsum by (plugin_name, method, operation) (\n  rate(\n    appsuite_provisioning_plugin_duration_seconds_count{\n      pod=~\"$pod\",\n      namespace=~\"$namespace\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{plugin_name}} - {{method}} - {{operation}}\n"
      }
     ]
    },
    {
     "title": "Average Storage Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (storage_class, method, operation) (\n  rate(\n    appsuite_provisioning_storage_duration_seconds_sum{\n      pod=~\"$pod\",\n      namespace=~\"$namespace\"\n    }[$__rate_interval]\n  )\n) /\nsum by (storage_class, method, operation) (\n  rate(\n    appsuite_provisioning_storage_duration_seconds_count{\n      pod=~\"$pod\",\n      namespace=~\"$namespace\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{storage_class}} - {{method}} - {{operation}}\n"
      }
     ]
    }
   ]
  },
  {
   "title": "IMAP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests (per-second)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(\n  rate(\n    appsuite_imap_commands_seconds_count{\n      pod=~\"$pod\"\n    }\n    [$__rate_interval]\n  )\n)\n",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(\n  rate(\n    appsuite_imap_commands_seconds_count{\n      status=~\"OK\",\n      pod=~\"$pod\"\n    }\n    [$__rate_interval]\n  )\n)\n",
       "legendFormat": "OK"
      },
      {
       "expr": "sum(\n  rate(\n    appsuite_imap_commands_seconds_count{\n      status!~\"OK\",\n      pod=~\"$pod\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "KO"
      }
     ]
    }
   ]
  }
 ]
}