{
 "title": "App Suite / Core-Middleware / JVM",
 "description": "App Suite Core Middleware JVM Dashboard\n",
 "tags": [
  "java",
  "app-suite"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(appsuite_version_info, namespace)"
   },
   {
    "name": "app",
    "query": "label_values(up{namespace=\"$namespace\"}, app)"
   },
   {
    "name": "pod",
    "query": "label_values(appsuite_version_info{namespace=\"$namespace\", app=~\".*$app.*\"}, pod)"
   },
   {
    "name": "mem_pools_heap",
    "query": "label_values(jvm_memory_used_bytes{pod=~\"$pod\", area=\"heap\"}, id)"
   },
   {
    "name": "mem_pools_nonheap",
    "query": "label_values(jvm_memory_used_bytes{pod=~\"$pod\", area=\"nonheap\"}, id)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "process_uptime_seconds{\n  pod=~\"$pod\"\n}\n"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(\n  jvm_memory_used_bytes{\n    pod=~\"$pod\",\n    area=\"heap\"\n  }\n) * 100 / sum(\n  jvm_memory_max_bytes{\n    pod=~\"$pod\",\n    area=\"heap\"\n  }\n)\n"
    }
   ]
  },
  {
   "title": "Non-Heap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(\n  jvm_memory_used_bytes{\n    pod=~\"$pod\",\n    area=\"nonheap\"\n  }\n) * 100 / sum(\n  jvm_memory_max_bytes{\n    pod=~\"$pod\",\n    area=\"nonheap\"\n  }\n)\n"
    }
   ]
  },
  {
   "title": "Memory Pools (Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "$mem_pools_heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "repeat": "mem_pools_heap",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(\n  jvm_memory_used_bytes{\n    pod=~\"$pod\",\n    area=\"heap\",\n    id=~\"$mem_pools_heap\"\n  }\n)\n",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(\n  jvm_memory_committed_bytes{\n    pod=~\"$pod\",\n    area=\"heap\",\n    id=~\"$mem_pools_heap\"\n  }\n)\n",
       "legendFormat": "Committed"
      },
      {
       "expr": "sum(\n  jvm_memory_max_bytes{\n    pod=~\"$pod\",\n    area=\"heap\",\n    id=~\"$mem_pools_heap\"\n  }\n)\n",
       "legendFormat": "Max"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Pools (Non-Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "$mem_pools_nonheap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "repeat": "mem_pools_nonheap",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(\n  jvm_memory_used_bytes{\n    pod=~\"$pod\",\n    area=\"nonheap\",\n    id=~\"$mem_pools_nonheap\"\n  }\n)\n",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(\n  jvm_memory_committed_bytes{\n    pod=~\"$pod\",\n    area=\"nonheap\",\n    id=~\"$mem_pools_nonheap\"\n  }\n)\n",
       "legendFormat": "Committed"
      },
      {
       "expr": "sum(\n  jvm_memory_max_bytes{\n    pod=~\"$pod\",\n    area=\"nonheap\",\n    id=~\"$mem_pools_nonheap\"\n  }\n)\n",
       "legendFormat": "Max"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(\n  jvm_gc_collection_seconds_sum{\n    pod=~\"$pod\"\n  }[$__rate_interval]\n) / rate(\n  jvm_gc_collection_seconds_count{\n    pod=~\"$pod\"\n  }[$__rate_interval]\n)\n",
       "legendFormat": "{{gc}}\n"
      }
     ]
    },
    {
     "title": "Collection",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(\n  jvm_gc_collection_seconds_count{\n    pod=~\"$pod\"\n  }[$__rate_interval]\n)\n",
       "legendFormat": "{{gc}}\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Classloading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Classes loaded",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_classes_loaded_classes{\n  pod=~\"$pod\"\n}\n",
       "legendFormat": "Loaded"
      }
     ]
    }
   ]
  },
  {
   "title": "Thread",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "targets": [
      {
       "expr": "jvm_threads_live_threads{\n  pod=~\"$pod\"\n}\n",
       "legendFormat": "Live\n"
      },
      {
       "expr": "jvm_threads_daemon_threads{\n  pod=~\"$pod\"\n}\n",
       "legendFormat": "Daemon"
      },
      {
       "expr": "jvm_threads_peak_threads{\n  pod=~\"$pod\"\n}\n",
       "legendFormat": "Peak"
      }
     ]
    },
    {
     "title": "Thread States",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "targets": [
      {
       "expr": "jvm_threads_states_threads{\n  pod=~\"$pod\"\n}\n",
       "legendFormat": "{{state}}\n"
      }
     ]
    }
   ]
  }
 ]
}