{{- if .Values.appsuiteSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "switchboard.appsuiteSecret" . }}
type: Opaque
data:
  token-login-secret: {{ required "appsuite.apiSecret required" .Values.appsuite.apiSecret | b64enc | quote }}
  webhook-secret: {{ required "appsuite.webhookSecret required" .Values.appsuite.webhookSecret | b64enc | quote }}
  signature-secret: {{ required "appsuite.signatureSecret required" .Values.appsuite.signatureSecret | b64enc | quote }}
{{- end -}}
