apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ox-common.names.fullname" . }}
  labels:
    {{- include "ox-common.labels.standard" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ox-common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      annotations: {{ toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        {{- include "ox-common.labels.podLabels" . | nindent 8 }}
    spec: {{ include "ox-common.pods.podSpec" (dict "podRoot" .Values "global" $ "context" . ) | nindent 6 }}
      containers:
        - name: main
          {{- include "ox-common.containers.securityContext" (dict "podRoot" .Values "context" . "global" $) | nindent 10 }}
          image: {{ include "ox-common.images.image" (dict "imageRoot" .Values.image "global" $ "context" . ) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{ include "switchboard.env" . | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort | default 8080 }}
              protocol: TCP
            - name: monitoring
              containerPort: 9090
              protocol: TCP
          {{- if .Values.probe.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: /live
              port: 9090
            {{- omit .Values.probe.liveness "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.probe.readiness.enabled }}
          readinessProbe:
            httpGet:
                path: /ready
                port: 9090
            {{- omit .Values.probe.readiness "enabled" | toYaml | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.jwks.enabled }}
          volumeMounts:
            - name: jwks-cert
              mountPath: /app/jwks-cert
              readOnly: true
          {{- end }}
      {{- if .Values.jwks.enabled }}
      volumes:
        - name: jwks-cert
          secret:
            secretName: {{ required "Please specify the JWKS secret name (jwks.secretName) containing tls.key and tls.crt" .Values.jwks.secretName | quote }}
      {{- end }}
