{{- /*
  If you enable the shared secret you will disable the JWKS functionality.
*/}}
{{- if .Values.jwtSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "switchboard.jwtSecret" . }}
type: Opaque
data:
  jwt-shared-secret: {{ required `Please specify a shared jwt secret (jwt.sharedSecret)` .Values.jwt.sharedSecret | b64enc | quote }}
{{- end -}}

