{{- if .Values.mysql.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ox-common.names.fullname" . }}-migrate-{{ .Release.Revision }}
  labels:
  {{- include "ox-common.labels.standard" . | nindent 4 }}
  annotations:
  {{ toYaml .Values.podAnnotations | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec: {{ include "ox-common.pods.podSpec" (dict "podRoot" .Values "global" $ "context" . ) | nindent 6 }}
      containers:
        - name: main
          {{- include "ox-common.containers.securityContext" (dict "podRoot" .Values "context" . "global" $) | nindent 10 }}
          image: {{ include "ox-common.images.image" (dict "imageRoot" .Values.image "global" $ "context" . ) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/bin/node", "src/migrate.js", "--db", "switchboard", "up"]
          env:
            - name: DATABASES
              value: "switchboard"
            - name: DB_SWITCHBOARD_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "switchboard.mysqlSecret" . }}
                  key: MYSQL_DATABASE
            - name: DB_SWITCHBOARD_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "switchboard.mysqlSecret" . }}
                  key: MYSQL_HOST
            - name: DB_SWITCHBOARD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "switchboard.mysqlSecret" . }}
                  key: MYSQL_PASSWORD
            - name: DB_SWITCHBOARD_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "switchboard.mysqlSecret" . }}
                  key: MYSQL_USER
      restartPolicy: OnFailure
{{- end -}}
