{{- if and (.Values.mysql.enabled) (not .Values.mysql.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "switchboard.mysqlSecret" . }}
  labels:
  {{- include "ox-common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  MYSQL_HOST: {{ include "ox-common.mysql.host" (dict "mysql" .Values.mysql "context" .) | b64enc }}
  MYSQL_DATABASE: {{ include "ox-common.mysql.database" (dict "mysql" .Values.mysql "context" .) | b64enc }}
  MYSQL_USER: {{ include "ox-common.mysql.user" (dict "mysql" .Values.mysql "context" .) | b64enc }}
  MYSQL_PASSWORD: {{ required `Please specify the users mysql password (mysql.password)` (include "ox-common.mysql.password" (dict "mysql" .Values.mysql "context" .)) | b64enc }}
{{- end -}}
