{{- if and (not .Values.vapid.existingSecret) .Values.vapid.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "switchboard.vapidSecret" . }}
type: Opaque
data:
  vapid-public-key: {{ .Values.vapid.publicKey | b64enc | quote }}
  vapid-private-key: {{ .Values.vapid.privateKey | b64enc | quote }}
{{- end -}}

