# Default values for core-imageconverter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  extras:
    monitoring:
      enabled: false

replicaCount: 1

defaultRegistry: registry.open-xchange.com

image:
  repository: "core-imageconverter"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations:
  logging.open-xchange.com/format: "appsuite-json"

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8005
  portHttps: 8014
  portLiveness: 8018

resources:
  requests:
    cpu: 500m
    memory: 1000Mi
  limits:
    cpu: 4000m
    memory: 2000Mi

nodeSelector: {}

tolerations: []

affinity: {}

probe:
  liveness:
    enabled: true
    periodSeconds: 10
    failureThreshold: 15

  readiness:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 5
    failureThreshold: 2
    timeoutSeconds: 5

  startup:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 30

remoteDebug:
  enabled: false
  # port: 8105

imageconverter:
  targetFormats: []
    # - "auto:200x150~cover"
    # - "auto:400x300~cover"
    # - "auto:600x400~cover"
    # - "auto:1920x1080~contain"
    # - "auto:1920x1080~cover"
  preConvert: {}
    # enabled: false
  # maxParallelRequests: 512
  # maxQueueLength: 128
  # maxAsyncQueueLengthPercentage: 400
  # processingTimeoutSeconds: 10
  # imageUserComment: ""
  cache:
    remoteCache: {}
      # url: https://optional-cache-host:8001/cache or blank (explicitly: "" value) to disable usage of CacheService in case global.core-cacheservice.enabled=true
    # maxEntries: 250000
    # maxSizeMegaBytes: -1
    # maxLifetimeSeconds: 2592000
    # cleanupPeriodSeconds: 300
    # maxLocalEntries: 1000
    # maxLocalLifetimeSeconds: 3600
    # localCleanupPeriodSeconds: 60
  # jvmHeapSizeMB: 1024

logging:
  debug: true
  logDir: /var/log/open-xchange/imageconverter
  logFile: imageconverter.log
  maxFileSize: 2MB
  maxTotalFileSize: 50GB
  maxIndex: 20
  queueSize: 2048
  root:
    level: INFO
    json: true
    logstash: false
    syslog: false
    file: false
  json:
    prettyPrint: false
  syslog:
    host: localhost
    port: 514
    facility: USER
  logger:
    - name: com.openexchange.imageconverter
      level: INFO

extras:
  monitoring:
    # -- Whether monitoring resources should be created, e.g. a `ConfigMap` containing the Grafana dashboards.
    enabled: false

remoteDebug:
  enabled: false
  port:
