apiVersion: v1
kind: Service
metadata:
  name: {{ include "ox-common.names.fullname" . }}
  labels:
    {{- include "ox-common.labels.standard" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8005
      protocol: TCP
      name: http
    - port: {{ .Values.service.portLiveness }}
      targetPort: 8018
      protocol: TCP
      name: http-live
    {{- if .Values.remoteDebug.enabled }}
    - port: {{ .Values.remoteDebug.port | default 8105 }}
      targetPort: {{ .Values.remoteDebug.port | default 8105 }}
      protocol: TCP
      name: debug
    {{- end }}
  selector:
    {{- include "ox-common.labels.matchLabels" . | nindent 4 }}
