apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ox-common.names.fullname" . }}
  labels:
    {{- include "ox-common.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ox-common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      annotations: {{ toYaml .Values.podAnnotations | nindent 8 }}
        checksum/commonEnv: {{ include "ox-common.appsuite.commonEnv" . | sha256sum }}
      labels:
        {{- include "ox-common.labels.podLabels" . | nindent 8 }}
    spec: {{ include "ox-common.pods.podSpec" (dict "podRoot" .Values "global" $ "context" . ) | nindent 6 }}
      containers:
        - name: main
          securityContext: {{ toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "ox-common.images.image" (dict "imageRoot" .Values.image "global" $ "context" . ) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.logging.root.json }}
            - name: CONSOLELOG
              value: "/dev/tty"
            {{- end }}
            {{- if .Values.documentConverter }}
            - name: DC_JVM_HEAP_SIZE_MB
              value: {{ .Values.documentConverter.jvmHeapSizeMB | default "768" | quote }}
            {{- end }}
            - name: RELEASE_NAMESPACE
              value: {{ .Release.Name | quote }}
            - name: POD_IP
              valueFrom:
                fieldRef:
                    fieldPath: status.podIP
            - name: LO_URL_BLACKLIST_FILE
              value: "/opt/open-xchange/documentconverter/etc/readerengine.blacklist"
            - name: LO_URL_WHITELIST_FILE
              value: "/opt/open-xchange/documentconverter/etc/readerengine.whitelist"
            {{- if .Values.documentConverter }}
            - name: LO_URL_LINK_LIMIT
              value: {{ .Values.documentConverter.urlLinkLimit | default 200 | quote }}
            - name: LO_URL_LINK_PROXY
              value: {{ (regexReplaceAll "^(http[s]?|ftp[s]?)://" (.Values.documentConverter.urlLinkProxy | default "") "" ) | quote }}
            {{- end }}
            {{- if .Values.remoteDebug.enabled }}
            - name: JAVA_DEBUG_OPTIONS
              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:{{ .Values.remoteDebug.port | default 8108 }}"
            {{- end }}
            {{- if .Values.env }}
              {{- toYaml .Values.env | nindent 12 }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-common-env
          ports:
            - name: http
              containerPort: 8008
              protocol: TCP
            - name: https
              containerPort: 8011
              protocol: TCP
            - name: http-live
              containerPort: 8017
              protocol: TCP
            {{- if .Values.remoteDebug.enabled }}
            - name: debug
              containerPort: {{ .Values.remoteDebug.port | default 8108 }}
              protocol: TCP
            {{- end }}
          {{- if .Values.probe.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: http-live
            {{- omit .Values.probe.liveness "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.probe.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: /documentconverterws
              port: http
            {{- omit .Values.probe.readiness "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.probe.startup.enabled }}
          startupProbe:
            httpGet:
              path: /health/liveness
              port: http-live
            {{- omit .Values.probe.startup "enabled" | toYaml | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: log-config
              mountPath: /opt/open-xchange/documentconverter/etc/logback.xml
              subPath: logback.xml
            - name: dc-config
              mountPath: /opt/open-xchange/documentconverter/etc/documentconverter.properties
              subPath: documentconverter.properties
            - name: dc-logs
              mountPath: /var/log/open-xchange/documentconverter
            - name: dc-spool
              mountPath: /var/spool/open-xchange
            - name: dc-urlallow
              mountPath: /opt/open-xchange/documentconverter/etc/readerengine.whitelist
              subPath: readerengine.whitelist
            - name: dc-urldeny
              mountPath: /opt/open-xchange/documentconverter/etc/readerengine.blacklist
              subPath: readerengine.blacklist
            {{- if (eq ( include "ox-common.java.ssl.enabled" . ) "true") }}
            - name: java-ssl-secrets
              mountPath: /opt/open-xchange/documentconverter/etc/security/
              readOnly: true
            {{- end }}
            {{- if .Values.persistence.enabled }}
            - name: pvc-dc-cache
              mountPath: {{ .Values.persistence.cacheDir.path }}
            {{- end }}
      volumes:
        - name: log-config
          configMap:
            name: {{ include "core-documentconverter.configmap" . }}
            items:
              - key: logback.xml
                path: logback.xml
        - name: dc-config
          configMap:
            name: {{ include "core-documentconverter.configmap" . }}
            items:
              - key: documentconverter.properties
                path: documentconverter.properties
        - name: dc-logs
          emptyDir: {}
        - name: dc-spool
          emptyDir: {}
        - name: dc-urlallow
          configMap:
            name: {{ include "core-documentconverter.configmap" . }}
            items:
              - key: readerengine.whitelist
                path: readerengine.whitelist
        - name: dc-urldeny
          configMap:
            name: {{ include "core-documentconverter.configmap" . }}
            items:
              - key: readerengine.blacklist
                path: readerengine.blacklist
        {{- if (eq ( include "ox-common.java.ssl.enabled" . ) "true") }}
        - name: java-ssl-secrets
          secret:
            secretName: {{ include "ox-common.java.ssl.secretName" . }}
            items:
              - key: {{ include "ox-common.java.ssl.secret.keyStoreKey" . }}
                path: java-ssl.ks
              {{- if eq ( include "ox-common.java.ssl.useTrustStore" . ) "true" }}
              - key: {{ include "ox-common.java.ssl.secret.trustStoreKey" . }}
                path: java-ssl.ts
              {{- end }}
        {{- end }}
        {{- if .Values.persistence.enabled }}
        - name: pvc-dc-cache
          {{- if not (empty .Values.persistence.existingClaim) }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
          {{- else }}
          {{- if .Values.persistence.cacheDir.hostPath }}
          hostPath:
            path: {{ .Values.persistence.cacheDir.hostPath }}
            type: DirectoryOrCreate
          {{- else }}
          persistentVolumeClaim:
            claimName: {{ template "core-documentconverter.volumeClaim.cacheDir" . }}
          {{- end }}
          {{- end }}
        {{- end }}
