apiVersion: v2
appVersion: 8.48.0
dependencies:
- name: ox-common
  repository: oci://registry.open-xchange.com/appsuite/charts
  version: 1.0.49
description: Document Converter core Helm chart
name: core-documentconverter
type: application
version: 2.46.1
