{{- if include "core-ui.hasDatabases" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.overrides.dbSecret }}
type: Opaque
stringData:
  # Comma-separated list of all enabled DBs (lowercase)
  {{- $dbNames := list -}}
  {{- range $name, $db := .Values.databases }}
    {{- $dbNames = append $dbNames $name -}}
  {{- end }}
  DATABASES: {{ join "," $dbNames | quote }}
  {{- $mysql := .Values.mysql -}}
  {{- range $name, $db := .Values.databases }}
  DB_{{ upper $name }}_HOST: {{ $db.host | default $mysql.host | default "localhost" |quote }}
  DB_{{ upper $name }}_PORT: {{ $db.port | default $mysql.port | default 3306 | quote }}
  DB_{{ upper $name }}_CONNECTIONS: {{ $db.connections | default 10 | quote }}
  DB_{{ upper $name }}_NAME: {{ $db.name | quote }}
  DB_{{ upper $name }}_USER: {{ $db.user | quote }}
  DB_{{ upper $name }}_PASSWORD: {{ $db.password | quote }}
  {{- end }}
{{- end }}
