apiVersion: v1
kind: Service
metadata:
  name: {{ include "ox-common.names.fullname" . }}
  labels:
    appsuite.ox.io/ui-provider: manifest
    {{- include "ox-common.labels.standard" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http
    - port: 9090
      targetPort: monitoring
      protocol: TCP
      name: monitoring
  selector:
    {{- include "ox-common.labels.matchLabels" . | nindent 4 }}
