{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "core-ui.fullname" . }}
spec:
  hosts:
    - {{ .Values.istio.hostname }}
  gateways:
    - {{ .Values.istio.gateway }}
  http:
  - match:
    - uri:
        prefix: /
    name: core-ui
    route:
      - destination:
        host: {{ include "core-ui.fullname" . }}
        port:
          number: 80
{{- end }}
