com.openexchange.documentconverter.cacheDir={{ include "core-documentconverter.cacheDir" . }}
com.openexchange.documentconverter.scratchDir=/var/spool/open-xchange/documentconverter/scratch

{{- if .Values.documentConverter }}

com.openexchange.documentconverter.useCool={{ .Values.documentConverter.useCool | default false }}
com.openexchange.documentconverter.coolUrl={{ include "core-documentconverter.coolUrl" . }}

com.openexchange.documentconverter.jobProcessorCount={{ .Values.documentConverter.processorCount | default 3 | int }}
com.openexchange.documentconverter.jobExecutionTimeoutMilliseconds={{ mul (.Values.documentConverter.processingTimeoutSeconds | default 60 | int64) 1000 }}
com.openexchange.documentconverter.jobQueueCountLimitHigh={{ .Values.documentConverter.jobQueueCountLimitHigh | default 40 | int }}
com.openexchange.documentconverter.jobQueueCountLimitLow={{ .Values.documentConverter.jobQueueCountLimitLow | default 25 | int }}
com.openexchange.documentconverter.jobQueueTimeoutSeconds={{ .Values.documentConverter.jobQueueTimeoutSeconds | default 300 | int }}
com.openexchange.documentconverter.jobAsyncQueueCountLimitHigh={{ .Values.documentConverter.jobAsyncQueueCountLimitHigh | default 1024 | int }}

{{- if .Values.documentConverter.urlLinkLimit }}
com.openexchange.documentconverter.urlLinkLimit={{ .Values.documentConverter.urlLinkLimit | default 200 | int64 }}
{{- end }}

{{- if .Values.documentConverter.urlLinkProxy }}
com.openexchange.documentconverter.urlLinkProxy={{ regexReplaceAll "^(http[s]?|ftp[s]?)://" (.Values.documentConverter.urlLinkProxy | default "") "" }}
{{- end }}

{{- if .Values.documentConverter.cache }}
{{- if or (and .Values.documentConverter.cache.remoteCache .Values.documentConverter.cache.remoteCache.url) (kindIs "string" .Values.documentConverter.cache.remoteCache.url) }}
com.openexchange.documentconverter.cacheServiceUrl={{ toString (.Values.documentConverter.cache.remoteCache.url | default "") }}
{{- else if or (index .Values "core-cacheservice").enabled (index .Values.global "core-cacheservice").enabled }}
com.openexchange.documentconverter.cacheServiceUrl={{ include "ox-common.cs.serverURL" . }}
{{- end }}
{{- $MAX_KEYCOUNT := (ternary 1000000 .Values.documentConverter.cache.maxEntries (eq .Values.documentConverter.cache.maxEntries nil)) | int64 }}
com.openexchange.documentconverter.maxCacheEntries={{ ternary -1 $MAX_KEYCOUNT (lt $MAX_KEYCOUNT 0) }}
{{- $MAX_SIZE_MB := (ternary -1 .Values.documentConverter.cache.maxSizeMegaBytes (eq .Values.documentConverter.cache.maxSizeMegaBytes nil)) | int64 }}
com.openexchange.documentconverter.maxCacheSizeMB={{ ternary -1 $MAX_SIZE_MB (lt $MAX_SIZE_MB 0) }}
{{- $MAX_LIFETIME_SECONDS := (ternary 2592000 .Values.documentConverter.cache.maxLifetimeSeconds (eq .Values.documentConverter.cache.maxLifetimeSeconds nil)) | int64 }}
com.openexchange.documentconverter.cacheEntryTimeoutSeconds={{ ternary -1 $MAX_LIFETIME_SECONDS (lt $MAX_LIFETIME_SECONDS 0) }}
{{- $MIN_FREE_SIZE_MB := (ternary 1024 .Values.documentConverter.cache.minFreeSizeMegaBytes (eq .Values.documentConverter.cache.minFreeSizeMegaBytes nil)) | int64 }}
com.openexchange.documentconverter.minFreeVolumeSizeMB={{ ternary 1 $MIN_FREE_SIZE_MB (le $MIN_FREE_SIZE_MB 0) }}
{{- $CLEANUP_PERIOD_SECONDS := (ternary 300 .Values.documentConverter.cache.cleanupPeriodSeconds (eq .Values.documentConverter.cache.cleanupPeriodSeconds nil)) | int64 }}
com.openexchange.documentconverter.cacheCleanupPeriodSeconds={{ ternary 0 $CLEANUP_PERIOD_SECONDS (lt $CLEANUP_PERIOD_SECONDS 0) }}
{{ end }}
{{- end }}
{{- if .Values.probe }}
{{- if .Values.probe.liveness }}
com.openexchange.documentconverter.probe.liveness.periodSeconds={{ .Values.probe.liveness.periodSeconds | default 10 | int }}
{{- end }}
{{- if .Values.probe.readiness }}
com.openexchange.documentconverter.probe.readiness.periodSeconds={{ .Values.probe.readiness.periodSeconds | default 5 | int }}
{{- end }}
{{- if .Values.documentConverter }}
com.openexchange.documentconverter.probe.readiness.downAfterUsedServiceUnavailabilitySeconds={{ .Values.documentConverter.readinessDownAfterUsedServiceUnavailabilitySeconds | default 300 | int }}
com.openexchange.documentconverter.probe.liveness.downAfterReadinessDownSeconds={{ .Values.documentConverter.livenessDownAfterReadinessDownSeconds | default 15 | int }}
com.openexchange.documentconverter.probe.readiness.upRecoveryPeriodSeconds={{ .Values.documentConverter.readinessUpUsedServiceRecoveryPeriodSeconds | default 20 | int }}
{{- end }}
{{- end }}
